### PR TITLE
Max allium intensity 22.125

### PR DESCRIPTION
**Pull request by platinum4**

### CODE REVIEW

**Comment by Quake4** [comment]
This intencity work on 1060?

**Comment by platinum4** [comment]
Yes, I have 5 of them on 2 mixed card rigs, works fine since 2.2.6pre

**Comment by Quake4** [comment]
MM have 3 miner for allium algo. Can you change it configs to this intensity and write me speed results?

**Comment by platinum4** [comment]
Yes I have to rebenchmark with no cpu miners, see recent open issue

**Comment by platinum4** [comment]
I can't get it to load in the extraargs it keeps getting overwritten; you can try this yourself as 22.25 doesn't mine.

**Comment by platinum4** [comment]
22.125, 22, 21 mine

**Comment by Quake4** [comment]
You must change config files isnt ps1 files. In ps1 files in miners has default config, if config not exists, created default. And all cases configuration readed from configure files.

**Comment by platinum4** [comment]
ok ill look to get you a comparison perhaps tomorrow

**Comment by Quake4** [comment]
22.125 not work on 1060.
21 by default.
You can change config.

**Comment by platinum4** [comment]
It's possible it doesn't work on this fork, it worked on tpruvot's but this is another build of it

**Comment by Quake4** [comment]
I choose intencity for all cards 10x0 family.
You can change [miner].config.txt to any needed values and MM use yours config for working.

**Pull request closed without merging**
