### PR TITLE
masks for cnv7/cnh, mask for lyra2v2-old (dredge)

### PR DESCRIPTION
**Pull request by platinum4**

### CODE REVIEW

**Comment by Quake4** [comment]
yes used in mph
"cryptonight-monero" = "Cryptonightv7"

not needed it first letter in uppercase. is auto conversion.
"cryptonightheavy" = "Cryptonightheavy"
"cryptonightv7" = "Cryptonightv7"

nowhere to be used:
"cryptonight-heavy" = "Cryptonightheavy"
"cryptonightmonero" = "Cryptonightv7"
"cryptonight_monero" = "Cryptonightv7"

**Comment by platinum4** [comment]
https://i.imgur.com/9LAKWrt.png

This is why I did this, tpruvot 2.3 is messed up because not accepting suggestions from outside world.  Sometimes code is not bulletproof.

**Comment by platinum4** [comment]
-a monero should be the flag here but because of naming mismatch you have it mining wrong algo to v7 stratum

**Comment by Quake4** [comment]
just isnt work: https://github.com/tpruvot/ccminer/pull/61

**Comment by Quake4** [comment]
your picture show v7 stratum.

**Comment by platinum4** [comment]
why is it mining cryptonight instead of v7

**Comment by platinum4** [comment]
tpruvot close my issue cuz i said hi to ystarnaud thats weak

**Pull request closed without merging**
