### PR TITLE
Add -q arg to ccminer launch lines

### PR DESCRIPTION
**Pull request by platinum4**
https://github.com/Quake4/MindMiner/issues/97

### CODE REVIEW

**Comment by platinum4** [comment]
Hi,

Do this.

**Comment by platinum4** [comment]
Take too long

**Comment by Quake4** [comment]
I test it and add.

**Comment by platinum4** [comment]
Need do

**Comment by platinum4** [comment]
Need do, i see you did for cpuminer opt

**Comment by Quake4** [comment]
2.63

**Pull request closed without merging**
