### PR TITLE
Update and rename srbm-cpu-20.ps1 to srbm-cpu-30.ps1

### PR DESCRIPTION
**Pull request by platinum4**
https://github.com/Quake4/MindMiner/issues/594

### CODE REVIEW

**Comment by Quake4** [comment]
where gpu?

**Comment by platinum4** [comment]
I'm not paid enough for that, add donate for me 0.01% 😎

**Comment by Quake4** [comment]
set MRR.config.txt => Target => +10% ;)

**Comment by platinum4** [comment]
oh no that would scare me then my rigs be advertised at $200/day like v6.1! ;]

**Comment by Quake4** [comment]
this bug is fixed

**Comment by platinum4** [comment]
yes i have watched the price updates it is smarter

**Comment by Quake4** [comment]
cn only for gpu

**Pull request merged**
