### PR TITLE
eres 0

### PR DESCRIPTION
**Pull request by platinum4**
No need to pre-load DAG on profit-switching

### CODE REVIEW

**Comment by Quake4** [comment]
this no preload. this preallocate buffer to can change dag size to next epoch.
i set buffer to one next epoch
what if we get to the time of switching epoch everything went smoothly.

**Comment by platinum4** [comment]
Still need do this, I watch NH and MPH switch from ETH to ETC to others often like DAG epoch 21 Hi

**Comment by Quake4** [comment]
what is the difference between "-eres 0" and "-eres 1"?

**Comment by platinum4** [comment]
0 means for DAG epoch 198 only 198 is generated nothing else
1 means for DAG epoch 198, 198 and 199 are generated; this is pointless if MPH or NH switches to UBQ or ETC which is DAG epoch 21 or 204, loading 199 for ETH does nothing.
eres values only helpful if you are mining on ethermine or dwarfpool and only one ethash coin on same epoch pathway like mining UBQ only at a UBQ pool at low epoch

**Comment by Quake4** [comment]
`
-eres   this setting is related to Ethereum mining stability. Every next Ethereum epoch requires a bit more GPU memory, miner can crash during reallocating GPU buffer for new DAG. 
   To avoid it, miner reserves a bit larger GPU buffer at startup, so it can process several epochs without buffer reallocation.
   This setting defines how many epochs miner must foresee when it reserves GPU buffer, i.e. how many epochs will be processed without buffer reallocation. Default value is 2.
`

**Comment by Quake4** [comment]
1 - allocate buffer + one epoch, not generate next epoch.

**Comment by Quake4** [comment]
?

**Pull request closed without merging**
